TARGET := heap01

RELRO := default
CANARY := 1
NX := 1

GLIBC_VERSION := 2.35
DOCKER_IMAGE := heap01
DOCKER_PORTS := 24006
DOCKER_TIMELIMIT := 30

PUBLISH_BUILD := $(TARGET)
PUBLISH_LIBC := libc.so.6
