FROM ubuntu:22.04

run apt-get -qq update && apt-get install -qq xinetd gcc

copy heap00 /heap00
run chmod 755 /heap00

copy flag.txt /

copy service.conf /service.conf
copy wrapper /wrapper
copy banner_fail /

EXPOSE 20000/TCP

cmd ["/usr/sbin/xinetd", "-filelog", "-", "-dontfork", "-f", "/service.conf"]
