name: sun24-mariner

services:
  rancher-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    privileged: true
    environment:
      - TLS_SAN=mariner.ctf.hackucf.org
    ports:
      - "24501:6443"   # Kubernetes API server (players connect here)
    tmpfs:
      - /run
      - /var/run
    mem_limit: 1500m
    cpus: 2.0
    pids_limit: 4096
