version: '3'
services:
  rancher-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6444:6444"  # Expose Rancher server on port 6444
      - "6443:6443"
    networks:
      - rancher-net
    volumes:
      # Use a named volume to share the TLS directory between services
      - ./attachments/client-ca.key:/var/lib/rancher/k3s/server/tls/client-ca.key
      - ./attachments/client-ca.crt:/var/lib/rancher/k3s/server/tls/client-ca.crt
      - ./attachments/server-ca.crt:/var/lib/rancher/k3s/server/tls/server-ca.crt

networks:
  rancher-net:
    driver: bridge
