name: sun24-file-islands-1

services:
  chal:
    build: ./src
    restart: unless-stopped
    ports:
    - "127.0.0.1:24303:8000"
    environment:
    - DOMAIN=file-islands.ctf.hackucf.org
    - FLAG=sun{lf1_us1ng_proc_f1les_1s_fUN}
    mem_limit: 256m
    cpus: 0.5
    pids_limit: 512
